#!/usr/bin/env bash





#### reminder-aur-yay-reinstall  ## yay-reinstall 

function yay-reinstall() {

    cat <<EOF
## https://github.com/Jguer/yay
## If you do not want to compile yay yourself you can use the builds generated by GitHub Actions.

pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si


## first use
 - Use yay -Y --gendb to generate a development package database for *-git packages that were installed without yay. This command should only be run once.
 - yay -Syu --devel will then check for development package updates
 - Use yay -Y --devel --save to make development package updates permanently enabled (yay and yay -Syu will then always check dev packages)


EOF
}
function reminder-aur-yay-reinstall () { yay-reinstall; }

#### END reminder-aur-yay-reinstall



#### reminder-aur-paru-reinstall

function reminder-aur-paru-reinstall () {

    cat <<EOF
pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si


## first use? 
 - paru --gendb
 - paru -Syu --devel
EOF
}
#### END reminder-aur-paru-reinstall
