#!/bin/bash
## http://www.webupd8.org/2009/12/upload-image-to-imgur-nautilus-actions.html

[[ -z $1 ]] && exit

#imgur(){

for i in "$@";do
curl -# -F "image"=@"$i" -F "key"="4907fcd89e761c6b07eeb8292d5a9b2a" https://imgur.com/api/upload.xml |\
grep -Eo '<[a-z_]+>http[^<]+' | sed 's/^<.\|_./\U&/g;s/_/ /;s/<\(.*\)>/\x1B[0;34m\1:\x1B[0m /'
done

#}