#!/usr/bin/env bash

#### systemd-other-user-spawner
#### spawn-other-user-systemd

## goal to "su" to another user mimicing an actual other-user-login without ssh or machinectl login
## inspired by https://unix.stackexchange.com/questions/641127/starting-a-systemd-user-instance-for-a-user-from-a-shell


### TODO: parse args properly
if [[ "${1,,}" =~ -+off ]]; then
    shift
    sudo -N systemctl stop user@$(id -u ${1})
    exit
fi

otheruser=${1}

id=$(id -u $otheruser)

sudo systemctl start user@$id

## added XDG_RUNTIME_DIR to trick x2-beta (added to x2-beta)
# exec sudo -u $otheruser   DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$id/bus  XDG_RUNTIME_DIR=/run/user/$id   systemd-run --user --scope --shell
exec sudo -N -i -H -u $otheruser   DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$id/bus  --  systemd-run  --user --scope --shell
